### ISSUE TITLE
Error on sending a message: "TypeError: no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by csterritt** [bemurphy/rushover#3]
Hey -- thanks for doing Rushover.

I'm running into a problem with a Rails 4.2.1 app, using Ruby 2.2.0.

Here's the results of trying it in a rails console (though I get the same result in a POST):

```
2.2.0 :001 > client = Rushover::Client.new "app-key"
 => #<Rushover::Client:0x007fe4bb341988 @token="app-key">
2.2.0 :002 > client.notify "user-key", "This is a message", :priority => 1, :title => "This is the title"
TypeError: no implicit conversion of nil into String
    from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/json-1.8.2/lib/json/common.rb:155:in `new'
from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/rushover-0.3.0/lib/rushover.rb:49:in `parse_response'
from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/rushover-0.3.0/lib/rushover.rb:59:in `post_json'
from /Users/chris/.rvm/gems/ruby-2.2.0@rails420/gems/rushover-0.3.0/lib/rushover.rb:21:in `notify'
```

Obviously, "app-key" and "user-key" are the correct Pushover-supplied values.

Thanks!

**Comment by bemurphy** [comment]
@csterritt thanks for the report.  I'm having trouble replicating the behavior unfortunately.  It sounds like though that JSON is trying to parse a nil value, that would trigger this exception, just not sure why there's a nil.

If you monkeypatch rushover in the app with an initializer with some debug code, it might help to see where the nil is sneaking in.

``` ruby
require "rushover"

module Rushover
  class Client
    def parse_response
      raw_response = begin
        rr = yield
        puts "rr: #{rr}"
        rr
      rescue RestClient::Exception => e
        puts "exception: #{e}"
        e.response
      end

      puts "raw_response: #{raw_response}"
      Response.new JSON.parse(raw_response)
    end
  end
end
```
